dist: trusty
sudo: required
language: node_js
node_js:
  - node
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-*.deb
